### ISSUE TITLE
Link shinyapps.io

### ISSUE THREAD

**Issue by aephidayatuloh** [trihanrevi/stadex#1]
Boleh ditambahkan link shinyapps.io dari aplikasi ini agar saya bisa akses secara online?

Terima kasih dan salam,
Aep

**Comment by trihanrevi** [comment]
Terimakasih sudah diingatkan pak. Untuk link shinyapps.io bisa dilihat pada bagian readme dan sudah bisa diakses secara online.

Salam hormat,
Tim developer Stadex
